
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author panto_mattia
 */
public class NewJFrame extends javax.swing.JFrame {

    gestioneFileBinari gest;
    ArrayList<cBottiglia> risultatiRicerca;
    int pos = 0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        risultatiRicerca = new ArrayList<cBottiglia>();
        
        try {
            gest = new gestioneFileBinari("cantina.bin");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println(gest.leggi(0).getAnnata());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome = new javax.swing.JTextField();
        txt_casaVin = new javax.swing.JTextField();
        txt_regione = new javax.swing.JTextField();
        cmb_tipo = new javax.swing.JComboBox<>();
        cmb_formato = new javax.swing.JComboBox<>();
        sldr_annata = new javax.swing.JSlider();
        btn_salva = new javax.swing.JButton();
        cmb_scelta = new javax.swing.JComboBox<>();
        btn_cerca = new javax.swing.JButton();
        txt_cerca = new javax.swing.JTextField();
        btn_indietro = new javax.swing.JButton();
        btn_avanti = new javax.swing.JButton();
        btn_elimina = new javax.swing.JButton();
        lbl_pos = new javax.swing.JLabel();
        lbl_anno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_immagine = new javax.swing.JButton();
        lbl_immagine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bianco", "Rosso", "Rosè" }));

        cmb_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.5", "0.75", "1" }));

        sldr_annata.setMaximum(2015);
        sldr_annata.setMinimum(1800);
        sldr_annata.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldr_annataMouseDragged(evt);
            }
        });

        btn_salva.setText("Salva");
        btn_salva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salvaMouseClicked(evt);
            }
        });

        cmb_scelta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Casa vinicola" }));

        btn_cerca.setText("cerca");
        btn_cerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cercaMouseClicked(evt);
            }
        });

        btn_indietro.setText("<");
        btn_indietro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_indietroMouseClicked(evt);
            }
        });

        btn_avanti.setText(">");
        btn_avanti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_avantiMouseClicked(evt);
            }
        });

        btn_elimina.setText("elimina questa bottiglia");
        btn_elimina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminaMouseClicked(evt);
            }
        });

        lbl_anno.setText("0000");

        jLabel1.setText("Nome");

        jLabel2.setText("Casa vinicola");

        jLabel3.setText("Regione/zona");

        btn_immagine.setText("Immagine");
        btn_immagine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_immagineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbl_pos))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nome)
                            .addComponent(txt_casaVin)
                            .addComponent(cmb_tipo, 0, 93, Short.MAX_VALUE)
                            .addComponent(cmb_formato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_salva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_regione, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmb_scelta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cerca)
                                .addComponent(txt_cerca))
                            .addGap(54, 54, 54))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_indietro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_avanti, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sldr_annata, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_anno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_immagine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_immagine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_scelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_pos)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_casaVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cerca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_avanti)
                            .addComponent(btn_indietro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldr_annata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_anno))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_regione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_salva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btn_elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_immagine)
                    .addComponent(lbl_immagine, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salvaMouseClicked
        String nome = txt_nome.getText();
        String casaVin = txt_casaVin.getText();
        String tipo = cmb_tipo.getItemAt(cmb_tipo.getSelectedIndex());        
        String formato = cmb_formato.getItemAt(cmb_formato.getSelectedIndex());
        String annata = String.valueOf(sldr_annata.getValue());
        String zona = txt_regione.getText();
        
        cBottiglia tBott = new cBottiglia(nome,casaVin,tipo,formato,annata,zona);
        
        gest.aggiungi(tBott);
        gest.salva();
        
    }//GEN-LAST:event_btn_salvaMouseClicked

    private void btn_cercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cercaMouseClicked
        String cerca = txt_cerca.getText();
        risultatiRicerca.clear();
        pos = 0;
        
        for(int i = 0; i < gest.numElementi(); i++){
            if(cmb_scelta.getSelectedIndex() == 0 && gest.leggi(i).getNome().equals(cerca)){
                risultatiRicerca.add(gest.leggi(i));
            }
            
            if(cmb_scelta.getSelectedIndex() == 1 && gest.leggi(i).getCasaVin().equals(cerca)){
                risultatiRicerca.add(gest.leggi(i));
            }
        }
        if(risultatiRicerca.size() > 0)
            scrivi();
    }//GEN-LAST:event_btn_cercaMouseClicked

    private void btn_indietroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_indietroMouseClicked
        pos --;
        if(pos < 0)
            pos = risultatiRicerca.size() - 1;

        scrivi();
    }//GEN-LAST:event_btn_indietroMouseClicked

    private void btn_avantiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_avantiMouseClicked
        pos ++;
        if(pos >= risultatiRicerca.size())
            pos = 0;
        
        scrivi();
    }//GEN-LAST:event_btn_avantiMouseClicked

    private void btn_eliminaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminaMouseClicked
        if(risultatiRicerca.size() > 0){
            gest.elimina(risultatiRicerca.get(pos));
            risultatiRicerca.remove(pos);
            gest.salva();

        }
        
        if(risultatiRicerca.size() != 0){
            pos = 0;
            scrivi();
        }
    }//GEN-LAST:event_btn_eliminaMouseClicked

    private void sldr_annataMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldr_annataMouseDragged
        lbl_anno.setText(Integer.toString(sldr_annata.getValue()));
    }//GEN-LAST:event_sldr_annataMouseDragged

    private void btn_immagineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_immagineMouseClicked
        String path;
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(fileChooser);
        if(result == 0){
            File selectedFile = fileChooser.getSelectedFile();
            path = selectedFile.getAbsolutePath();  
        }else{
            path = "";
        }
        
        lbl_immagine.setText(path);
    }//GEN-LAST:event_btn_immagineMouseClicked
    
    public void scrivi(){
        String nome = risultatiRicerca.get(pos).getNome();
        String casaVin = risultatiRicerca.get(pos).getCasaVin();
        String tipo = risultatiRicerca.get(pos).getTipo();       
        String formato = risultatiRicerca.get(pos).getFormato();
        String annata = risultatiRicerca.get(pos).getAnnata();
        String zona = risultatiRicerca.get(pos).getZona();
        lbl_pos.setText(String.valueOf(pos));
        lbl_anno.setText(annata);
        txt_nome.setText(nome);
        txt_casaVin.setText(casaVin);
        if(tipo.equals("Bianco")){
            cmb_tipo.setSelectedIndex(0);
        }
        if(tipo.equals("Rosso")){
            cmb_tipo.setSelectedIndex(1);
        }
        if(tipo.equals("Rosè")){
            cmb_tipo.setSelectedIndex(2);
        }
        
        if(formato.equals("0.5")){
            cmb_formato.setSelectedIndex(0);
        }
        if(formato.equals("0.75")){
            cmb_formato.setSelectedIndex(1);
        }
        if(formato.equals("1")){
            cmb_formato.setSelectedIndex(2);
        }
        
        sldr_annata.setValue(Integer.valueOf(annata));
        txt_regione.setText(zona);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avanti;
    private javax.swing.JButton btn_cerca;
    private javax.swing.JButton btn_elimina;
    private javax.swing.JButton btn_immagine;
    private javax.swing.JButton btn_indietro;
    private javax.swing.JButton btn_salva;
    private javax.swing.JComboBox<String> cmb_formato;
    private javax.swing.JComboBox<String> cmb_scelta;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_anno;
    private javax.swing.JLabel lbl_immagine;
    private javax.swing.JLabel lbl_pos;
    private javax.swing.JSlider sldr_annata;
    private javax.swing.JTextField txt_casaVin;
    private javax.swing.JTextField txt_cerca;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_regione;
    // End of variables declaration//GEN-END:variables
}
